version: '3'
services: 
    flask:
        build: .
        command: gunicorn -b 0.0.0.0:5000 main:app --reload
        environment: 
            - FLASK_APP=main.py
            - FLASK_DEBUG=1
            - PYTHONBUFFERED=True
        ports: 
            - "5000:5000"
        volumes:
            - ./:/root